import { Content } from './content.interface';

export const CONTENT_ITEMS: Content[] = [
	{
		_id: 'content-1',
		type: 'video',
		title: 'Aurora Tactics — Season 3 Trailer',
		description: 'New platforms, new factions, drifting into the aurora zone.',
		mediaUrl: 'https://example.com/media/aurora-s3-trailer.mp4',
		thumbnail: 'https://picsum.photos/seed/content-1/500/900',
		worldId: 'world-aurora',
		gameId: 'game-aurora-tactics',
		creator: { playerId: 'player-2', name: 'Nova Voss', avatar: 'https://i.pravatar.cc/150?u=player-2' },
		likeCount: 4210,
		commentCount: 312,
		createdAt: '2026-08-28T10:00:00Z',
	},
	{
		_id: 'content-2',
		type: 'comic',
		title: 'Emberfall #12: The Living Forge',
		description: 'Kestrel confronts the forge-wraith at the heart of the volcano.',
		mediaUrl: 'https://picsum.photos/seed/content-2-full/900/1400',
		thumbnail: 'https://picsum.photos/seed/content-2/500/900',
		worldId: 'world-ember',
		creator: { playerId: 'player-3', name: 'Studio Cindergate', avatar: 'https://i.pravatar.cc/150?u=player-3' },
		likeCount: 1820,
		commentCount: 96,
		createdAt: '2026-08-25T14:30:00Z',
	},
	{
		_id: 'content-3',
		type: 'video',
		title: 'Glassdive: 40-minute deep run',
		description: 'Full team clears the Cathedral vault without surfacing once.',
		mediaUrl: 'https://example.com/media/glassdive-deep-run.mp4',
		thumbnail: 'https://picsum.photos/seed/content-3/500/900',
		worldId: 'world-tide',
		gameId: 'game-glassdive',
		creator: { playerId: 'player-4', name: 'Reef Runner', avatar: 'https://i.pravatar.cc/150?u=player-4' },
		likeCount: 980,
		commentCount: 54,
		createdAt: '2026-08-20T09:15:00Z',
	},
	{
		_id: 'content-4',
		type: 'news',
		title: 'Nullpoint Relay hits 1M station-days survived',
		description: 'The community milestone unlocks a new conduit skin for everyone.',
		mediaUrl: 'https://picsum.photos/seed/content-4-full/900/600',
		thumbnail: 'https://picsum.photos/seed/content-4/500/900',
		worldId: 'world-nullpoint',
		gameId: 'game-nullpoint-relay',
		creator: { playerId: 'player-5', name: 'WAW Newsroom', avatar: 'https://i.pravatar.cc/150?u=player-5' },
		likeCount: 3110,
		commentCount: 201,
		createdAt: '2026-08-30T08:00:00Z',
	},
	{
		_id: 'content-5',
		type: 'character',
		title: 'Character Spotlight: Kestrel Ashgrave',
		description: 'The exiled smith who forged the first living-fire blade.',
		mediaUrl: 'https://picsum.photos/seed/content-5-full/900/1200',
		thumbnail: 'https://picsum.photos/seed/content-5/500/900',
		worldId: 'world-ember',
		gameId: 'game-emberforge',
		creator: { playerId: 'player-3', name: 'Studio Cindergate', avatar: 'https://i.pravatar.cc/150?u=player-3' },
		likeCount: 2440,
		commentCount: 140,
		createdAt: '2026-08-18T12:00:00Z',
	},
	{
		_id: 'content-6',
		type: 'video',
		title: 'Nullpoint Relay: speedrun WR attempt',
		description: 'Can the station survive 500 days without a single blackout?',
		mediaUrl: 'https://example.com/media/nullpoint-speedrun.mp4',
		thumbnail: 'https://picsum.photos/seed/content-6/500/900',
		worldId: 'world-nullpoint',
		gameId: 'game-nullpoint-relay',
		creator: { playerId: 'player-1', name: 'You', avatar: 'https://i.pravatar.cc/150?u=player-1' },
		likeCount: 640,
		commentCount: 41,
		createdAt: '2026-08-31T18:45:00Z',
	},
	{
		_id: 'content-7',
		type: 'book',
		title: 'Tideglass: Salvage Log Vol. 2',
		description: 'Field notes from the deepest dives into the Cathedral ruins.',
		mediaUrl: 'https://picsum.photos/seed/content-7-full/900/1300',
		thumbnail: 'https://picsum.photos/seed/content-7/500/900',
		worldId: 'world-tide',
		creator: { playerId: 'player-4', name: 'Reef Runner', avatar: 'https://i.pravatar.cc/150?u=player-4' },
		likeCount: 510,
		commentCount: 28,
		createdAt: '2026-08-14T07:20:00Z',
	},
	{
		_id: 'content-8',
		type: 'video',
		title: 'Aurora Drift: floating city timelapse',
		description: 'A full day-night cycle over the capital platform.',
		mediaUrl: 'https://example.com/media/aurora-timelapse.mp4',
		thumbnail: 'https://picsum.photos/seed/content-8/500/900',
		worldId: 'world-aurora',
		creator: { playerId: 'player-2', name: 'Nova Voss', avatar: 'https://i.pravatar.cc/150?u=player-2' },
		likeCount: 1290,
		commentCount: 77,
		createdAt: '2026-08-10T16:00:00Z',
	},
];
