import { Player } from './player.interface';

export const PLAYERS: Player[] = [
	{
		_id: 'player-1',
		name: 'You',
		avatar: 'https://i.pravatar.cc/150?u=player-1',
		bio: 'Exploring every WAW world one platform at a time.',
		achievementIds: ['ach-aurora-first-drift', 'ach-ember-first-forge', 'ach-null-500'],
		favoriteWorldIds: ['world-nullpoint'],
		favoriteGameIds: ['game-nullpoint-relay'],
		followedWorldIds: ['world-aurora', 'world-nullpoint'],
		followedGameIds: ['game-aurora-tactics', 'game-nullpoint-relay'],
		followedPlayerIds: ['player-2', 'player-5'],
		friendIds: ['player-2', 'player-3'],
		recentlyPlayedGameIds: ['game-nullpoint-relay', 'game-aurora-tactics', 'game-emberforge'],
		activity: [
			{ _id: 'act-1', text: 'Unlocked "500 Station-Days" in Nullpoint Relay', timestamp: '2026-08-31T19:00:00Z' },
			{ _id: 'act-2', text: 'Started following Aurora Drift', timestamp: '2026-08-27T11:00:00Z' },
			{ _id: 'act-3', text: 'Favorited Nullpoint Relay', timestamp: '2026-08-22T09:30:00Z' },
		],
	},
	{
		_id: 'player-2',
		name: 'Nova Voss',
		avatar: 'https://i.pravatar.cc/150?u=player-2',
		bio: 'Aurora Tactics ladder climber and lore archivist.',
		achievementIds: ['ach-aurora-first-drift', 'ach-aurora-flawless'],
		favoriteWorldIds: ['world-aurora'],
		favoriteGameIds: ['game-aurora-tactics'],
		followedWorldIds: ['world-aurora'],
		followedGameIds: ['game-aurora-tactics'],
		followedPlayerIds: ['player-1'],
		friendIds: ['player-1'],
		recentlyPlayedGameIds: ['game-aurora-tactics'],
		activity: [{ _id: 'act-4', text: 'Achieved "Flawless Skirmish"', timestamp: '2026-08-29T15:00:00Z' }],
	},
	{
		_id: 'player-3',
		name: 'Studio Cindergate',
		avatar: 'https://i.pravatar.cc/150?u=player-3',
		bio: 'Making Emberfall comics and running the Emberforge crafting meta.',
		achievementIds: ['ach-ember-first-forge', 'ach-ember-survivor'],
		favoriteWorldIds: ['world-ember'],
		favoriteGameIds: ['game-emberforge'],
		followedWorldIds: ['world-ember'],
		followedGameIds: ['game-emberforge'],
		followedPlayerIds: [],
		friendIds: ['player-1'],
		recentlyPlayedGameIds: ['game-emberforge'],
		activity: [{ _id: 'act-5', text: 'Published "Emberfall #12: The Living Forge"', timestamp: '2026-08-25T14:30:00Z' }],
	},
	{
		_id: 'player-4',
		name: 'Reef Runner',
		avatar: 'https://i.pravatar.cc/150?u=player-4',
		bio: 'Glassdive salvage lead. Ask me about oxygen routes.',
		achievementIds: ['ach-glassdive-deep'],
		favoriteWorldIds: ['world-tide'],
		favoriteGameIds: ['game-glassdive'],
		followedWorldIds: ['world-tide'],
		followedGameIds: ['game-glassdive'],
		followedPlayerIds: [],
		friendIds: [],
		recentlyPlayedGameIds: ['game-glassdive'],
		activity: [{ _id: 'act-6', text: 'Cleared the Cathedral vault in one dive', timestamp: '2026-08-20T09:15:00Z' }],
	},
	{
		_id: 'player-5',
		name: 'WAW Newsroom',
		avatar: 'https://i.pravatar.cc/150?u=player-5',
		bio: 'Official news and milestones from across every WAW world.',
		achievementIds: ['ach-null-500'],
		favoriteWorldIds: [],
		favoriteGameIds: [],
		followedWorldIds: ['world-aurora', 'world-ember', 'world-tide', 'world-nullpoint'],
		followedGameIds: [],
		followedPlayerIds: [],
		friendIds: [],
		recentlyPlayedGameIds: [],
		activity: [{ _id: 'act-7', text: 'Posted "Nullpoint Relay hits 1M station-days survived"', timestamp: '2026-08-30T08:00:00Z' }],
	},
];

export const CURRENT_PLAYER_ID = 'player-1';
